### ISSUE TITLE
Connection 'retrieve_object'

### ISSUE THREAD

**Issue by TenanATC** [talegari/safer#2]
Is it possible for the 'conn' argument in 'retrieve_object' to be a URL or other non-local location?

Reading the files from anything other than a local file system returns "Path ... does not exist".  Is this functionality that can easily be added either within safer or is there a work-around?

Thanks!
Matt

**Comment by TenanATC** [comment]
> Is it possible for the 'conn' argument in 'retrieve_object' to be a URL or other non-local location?
> 
> Reading the files from anything other than a local file system returns "Path ... does not exist". Is this functionality that can easily be added either within safer or is there a work-around?
> 
> Thanks!
> Matt

There is actually an easy work-around for this by specifying the connection type with url().  I wonder if this is worth adding or if it is something the end-user should just add when necessary?  

EDIT: This appears to only work with ascii files in my current (limited) experience.

**Comment by talegari** [comment]
@TenanATC  Thanks for pointing out this issue.

Using `url()` from the user end might be a good idea to keep a connection input generic enough. I have not really worked with `url` based connections, please suggest if you ideas to test this feature out.

**Comment by talegari** [comment]
Using url() from the user end might be a good idea
