### ISSUE TITLE
R Safer Package incompatibility with R version 3.5.2

### ISSUE THREAD

**Issue by Vini875** [talegari/safer#5]
Dear All,

I am facing an issue where the SAFER Package is not available in R version 3.5.2, as we did used this in our code for a prior version so moving to 3.5.2, why is it not available and any alternatives we have to do a similar activity as Safer (if it cannot be made available in R version 3.5.2).

Appreciate your valuable inputs.

**Comment by talegari** [comment]
`safer` depends on R (≥ 3.3.0). IMHO, it should work on 3.5.2. CRAN [checks](https://cran.r-project.org/web/checks/check_results_safer.html) appear clean too.

Let me know the error message and any other relevant details.
